# Generated by Django 2.2 on 2019-04-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='id',
        ),
        migrations.AlterField(
            model_name='protein',
            name='accession',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
