# Generated by Django 2.2.1 on 2019-05-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20190430_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peptide',
            fields=[
                ('sequence', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('requests', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=3)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpanGroup',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=3)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpanGroup_Regions',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.Region')),
                ('span_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.SpanGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Peptide_SpanGroups',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.Peptide')),
                ('span_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.SpanGroup')),
            ],
        ),
    ]
