# Generated by Django 2.2.1 on 2019-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_peptide_peptide_spangroups_region_spangroup_spangroup_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='spangroup',
            name='members',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
